let btn=document.getElementById("btn");
console.log(btn);
btn.setAttribute("name","form_1")// two value can be pass through hare first is name and seconf is value......
btn.setAttribute("class","new class")// add class attribute and calss name is new class....
let getattribute=btn.getAttribute("name1");// get the attribute......
console.log(`find the value of name1 attribute = ${getattribute}`);

let removeattribute=btn.removeAttribute("name1")// remove attribute...........
let checkattribute=btn.hasAttribute("name")// for check attribute is or not ?............
console.log(checkattribute);

