let apnd=document.getElementById("append");
console.log(apnd);
let h1=document.createElement('h1');// createElement is a method use for creating the value tags..
// where 'h1' is crating tag..


apnd.appendChild(h1);// apendChild() is a function add the tag.......
// let text=document.createTextNode("this text created by createTextNode..")//text create adding through method......
// h1.appendChild(text);// text append inside the h1 tag...
h1.textContent="Text Content added through properties"// text add through textContent properties....




h1.className="clsname";// this is for add class name in the h1 tag.......
h1.className="clsname clsname1";// this is for multiple classname....
h1.id="addId";// this properties add for id ......

let body=document.body.appendChild(h1);// this is for tag position set ...
console.log(body);

// text read by .textContent,
let para=document.getElementById("read");
console.log(para.textContent);// text content read by textContent method...

let list1=document.getElementById("list");// add a list by append method...
console.log(list1);
let item=document.createElement("li");// create child by document.createElement() method...
item.textContent="new list 5";// add text content inside the created list...
list1.appendChild(item);//add the created list this will make last child of all child components .....






