// let txt=document.getElementById("box")
// console.log(txt.className);
// txt.className += " dim2";// this is first way to add css through java scipt.......

// console.log(txt.className)

// this is second way to check and add class through java script...............
let txt=document.getElementById("box");
console.log(txt.classList);// this is second way how to check atteched class throu classlist.....
let csslist=txt.classList;

for(let i of csslist){   // this is for of loop using for acess atteched cssclass.........
    console.log(i);
};

csslist.add("newclass")// this is second way to add class in html through java script.........
csslist.remove("dim")// this is using for remove atteched class in html.........
csslist.replace("color","replacecss")// this is replace method using for replace the class by two arguments pass first is which is replce and second is replace new class........
csslist.contains("enter class name");// this is for check given class atteched or not.............
let check_class=csslist.contains("color");
console.log(check_class);

let toggle=csslist.toggle("in_class");// this is toggle method using for if given class is atteched then remove atteched class if given class is not atteched then add given class.........
console.log(toggle);

