// get computed css- to checking already working css in this element.......
let btn=document.getElementById("newbtn");
console.log(btn);

let css=getComputedStyle(btn);// this method use for checking atteched css in this elements..........
// console.log(css);// there is show all atteched css......
console.log(css.padding)// this is checking for particuler css.......
console.log(`text color code ${css.color}`)// this is checking for particuler css.......
