let btn=document.getElementById("btn1");
let btn1=document.getElementById("btn2");
let btn2=document.getElementById("btn3");
console.log(btn);
btn.style.cssText="background-color: red; color:white; border-radius:5px;";// this is first way set to inline css..........
btn1.setAttribute("style","background-color:green; color:white;border-radius:5px");// this is second way to set inline css........
btn2.style.background='orange';// this is one by one change style methd one time only one style will be change..........
