// this is element select by ID method......... 

let elm1=document.getElementById("list1");// document is method/object and getElementById is a properties of object........

        console.log(elm1);
        console.log(elm1.innerHTML);//(value get from inner HTML) innerHTML is a propertie to access the inner HTML of an element/object ....
        elm1.innerHTML="<p> hello this is value set propertie<p>";// (value set in inner HTML)